### ISSUE TITLE
Icon text alternative is not accessible

### ISSUE THREAD

**Issue by garethslinn** [w3c/coga#353]
### Context
To enhance the accessibility of the document for screen readers, particularly focusing on how icons are described. This change is intended as a guide to improve the user experience for visually impaired users.

### Issue
The 'start here' icon contains graphic text that is not accessible to a screen reader.  Due to the method of implementation i.e. css background we can approach this with minimal disruption.  

### Current CSS Implementation

```css
#user_needs section.objective:nth-of-type(1) h3::before {
    content: url(img/StartHere.svg);
}
```

### Suggested enhancement

```css
#user_needs section.objective:nth-of-type(1) h3::before {
    display: inline-block;
    background: url(img/StartHere.svg) no-repeat;
    background-size: contain;
    content: "Start Here: "; 
    color: transparent; 
}
```

### Note
This works well in VoiceOver however it may require some adjustment and rigorous testing on different platforms.
